.PHONY: init plan apply destroy output

# Run from this directory: cd infra && make init
# Populate terraform.tfvars from terraform.tfvars.example before running plan/apply.

init:
	terraform init

plan:
	terraform plan

apply:
	terraform apply

destroy:
	terraform destroy

output:
	terraform output
