"""Prompt builders and static schema catalog for the Analytics Agent.

All Claude prompts live here. Business logic (validation, execution) lives
elsewhere. Nothing in this file makes network calls.

Two Claude calls happen per question:
  1. SQL generation: system prompt with embedded Gold schemas + user question
     -> <sql> block + <assumptions> block
  2. Insight generation: results + question -> 2-3 sentence plain-English insight

The static GOLD_TABLE_CATALOG encodes business meaning derived from live
Athena query results. It is the fallback description layer used when dbt
catalog.json has not been populated yet (first pipeline run), and it also
adds accepted-value hints that dbt column descriptions do not capture.
"""

from typing import Any, Final

from agent.schema import AllSchemas

# ---------------------------------------------------------------------------
# Static Gold table catalog
#
# Column descriptions and accepted-value hints sourced from live Athena
# query results against the AWS dev environment. These descriptions enrich
# the Glue physical schema that SchemaResolver loads at startup.
# ---------------------------------------------------------------------------

GOLD_TABLE_CATALOG: Final[dict[str, dict[str, str]]] = {
    "monthly_revenue_trend": {
        "__table__": (
            "Monthly aggregated revenue and order metrics across the full platform. "
            "One row per calendar month. Use this table for revenue trends, growth "
            "analysis, and order volume over time. Data is available from 2024 onwards."
        ),
        "order_year": "Calendar year of the orders (integer, e.g. 2024). Filter here first for year-scoped questions.",
        "order_month": "Calendar month number 1-12 (integer).",
        "total_orders": "Count of all orders placed in this month, regardless of status.",
        "unique_customers": "Count of distinct customers who placed at least one order this month.",
        "total_revenue": "Sum of order value in GBP for all completed orders in this month.",
        "cancelled_orders": "Count of orders cancelled this month.",
    },
    "customer_segments": {
        "__table__": (
            "One row per customer with lifetime metrics and a frequency segment band. "
            "Use for customer analysis, lifetime value queries, and segmentation by geography or behaviour."
        ),
        "customer_id": "Unique customer identifier (integer).",
        "first_name": "Customer first name.",
        "last_name": "Customer last name.",
        "email": "Customer email address.",
        "country": (
            "Country of the customer. Known values: France, Germany, United Kingdom, "
            "Spain, Italy, Netherlands, Sweden, Poland, Belgium, and others."
        ),
        "signup_date": "Date the customer registered (DATE type, e.g. '2024-04-13').",
        "total_orders": "Total number of orders this customer has ever placed.",
        "lifetime_value": "Total revenue generated by this customer across all completed orders.",
        "first_order_date": "Date of the customer's first completed order (DATE type).",
        "last_order_date": "Date of the customer's most recent completed order (DATE type).",
        "customer_frequency_band": (
            "RFM-style segment label. "
            "Values: 'vip' (high-value repeat buyers), 'core' (regular buyers), "
            "'occasional' (infrequent buyers), 'new' (first-time buyers)."
        ),
    },
    "payment_method_performance": {
        "__table__": (
            "Aggregated payment processing metrics per payment method. "
            "One row per payment method. Use for payment conversion rates, "
            "failed transaction analysis, and revenue capture by method."
        ),
        "payment_method": (
            "Payment method name. "
            "Values: 'credit_card', 'debit_card', 'paypal', 'apple_pay', 'crypto'."
        ),
        "total_transactions": "Total number of payment attempts for this method.",
        "successful": "Count of transactions that completed successfully.",
        "failed": "Count of failed transactions.",
        "refunded": "Count of refunded transactions.",
        "success_per_pct": "Transaction success rate as a percentage (0-100 scale, e.g. 41.44).",
        "total_processed": "Total monetary value attempted through this payment method (GBP).",
        "revenue_captured": "Total monetary value successfully captured — successful transactions only (GBP).",
    },
    "carrier_delivery_performance": {
        "__table__": (
            "Delivery performance metrics per shipping carrier. "
            "One row per carrier. Use for logistics analysis, delivery time comparisons, "
            "and carrier success rate questions."
        ),
        "carrier": "Carrier name. Values: 'Royal Mail', 'UPS', 'FedEx', 'DHL'.",
        "total_shipments": "Total shipments assigned to this carrier.",
        "delivered": "Count of shipments successfully delivered.",
        "failed": "Count of failed or lost shipments.",
        "delivery_success_pct": (
            "Delivery success rate as a percentage (0-100 scale). "
            "Typical range across carriers: 50-55%."
        ),
        "avg_delivery_days": "Average number of days from dispatch to delivery.",
        "fastest_delivery_days": "Minimum delivery days observed for this carrier.",
        "slowest_delivery_days": "Maximum delivery days observed for this carrier.",
    },
    "product_category_performance": {
        "__table__": (
            "Sales performance metrics grouped by product category and brand. "
            "One row per category-brand combination. Use for product performance, "
            "category analysis, and brand comparisons."
        ),
        "category": "Product category name. Primary value: 'Electronics'.",
        "brand": "Brand name within the category (e.g. Nexus, SurfPro, PageTurner, HighGear).",
        "total_product": "Count of distinct products for this brand.",
        "products_in_category": "Total count of products in the parent category across all brands.",
        "total_units_sold": "Total units sold across all products in this category-brand group.",
        "total_revenue": "Total revenue generated by this category-brand group (GBP).",
        "avg_revenue_per_unit": "Average revenue per unit sold (GBP).",
    },
    "revenue_by_country": {
        "__table__": (
            "Revenue and order metrics aggregated by customer country. "
            "One row per country. Use for geographic analysis and market comparisons. "
            "Germany is the highest-revenue market."
        ),
        "country": (
            "Customer country name. Known values: Germany, France, United Kingdom, "
            "Spain, Italy, Netherlands, Sweden, Poland, and others."
        ),
        "total_orders": "Total orders placed by customers in this country.",
        "total_customers": "Count of distinct customers from this country.",
        "total_revenue": "Total revenue from customers in this country (GBP).",
        "avg_order_value": "Average value per order for customers in this country (GBP).",
    },
    "top_selling_products": {
        "__table__": (
            "Individual product sales performance ranked by revenue. "
            "One row per product. Use for product-level analysis, top-N product questions, "
            "and SKU performance. The rank column enables direct top-N filtering."
        ),
        "product_id": "Unique product identifier (integer).",
        "product_name": "Full product name (e.g. 'Rapture Ultra Electronics').",
        "category": "Product category (e.g. 'Electronics').",
        "brand": "Product brand (e.g. 'Signature').",
        "total_orders": "Number of orders that included this product.",
        "total_units_sold": "Total units of this product sold.",
        "total_revenue": "Total revenue generated by this product (GBP).",
        "avg_revenue_per_unit": "Average selling price per unit (GBP).",
        "rank": "Revenue rank across all products. 1 = highest revenue product.",
    },
}

# ---------------------------------------------------------------------------
# Tool definition — get_schema fallback
#
# Claude can call this tool to retrieve detailed schema for a specific table
# during the SQL generation turn. Not used in the normal path because all
# schemas are already embedded in the system prompt. Available for edge cases
# where Claude needs to double-check a column or accepted value.
# ---------------------------------------------------------------------------

GET_SCHEMA_TOOL: Final[dict[str, Any]] = {
    "name": "get_schema",
    "description": (
        "Retrieve the full schema for a specific Gold table by name. "
        "Use this only when you need more detail about a table that is not already "
        "clear from the system prompt. In normal operation all schemas are already "
        "embedded — call this only if you are uncertain about a column name or type."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "table_name": {
                "type": "string",
                "description": (
                    "The exact table name as it appears in the Gold catalog, "
                    "e.g. 'monthly_revenue_trend'."
                ),
            }
        },
        "required": ["table_name"],
    },
}

# ---------------------------------------------------------------------------
# System prompt builder — SQL generation
# ---------------------------------------------------------------------------

_SQL_SYSTEM_HEADER = """\
You are a read-only analytics agent for an e-commerce data platform.
Your job is to answer questions about business performance by \
querying the Gold layer of the data warehouse using Amazon Athena SQL (Presto/Trino dialect).
Questions may be asked in any language. Always respond in the same language as the question.

## Rules you must follow

1. Only generate SELECT statements. Never use DROP, DELETE, INSERT, UPDATE, \
CREATE, ALTER, or TRUNCATE anywhere in the query, including inside CTEs or subqueries.
2. Only query tables in the {gold_database} database. Never reference Bronze, Silver, \
or any other database.
3. Always include a LIMIT clause. Never return more than {max_rows} rows.
4. Use Athena SQL syntax: single quotes for string literals, DATE 'YYYY-MM-DD' for \
date literals, CURRENT_DATE for today's date. Do not use MySQL-specific functions.
5. These are pre-aggregated Gold tables, not raw transaction tables. \
There is no raw orders, customers, or payments table — use the Gold aggregations directly.
6. State every assumption you make about how the question maps to the data.

## Output format

Always respond in exactly this structure — no text before or after:

<sql>
SELECT ...
FROM ...
LIMIT n
</sql>
<assumptions>
- Table: <name> — <reason for choosing this table>
- Filter: <what filter was applied and why, or 'none'>
- Note: <any interpretation of ambiguous terms in the question>
</assumptions>

## Gold tables available

{schema_text}
"""


def build_system_prompt(
    schemas: AllSchemas,
    gold_database: str,
    max_rows: int = 1000,
) -> str:
    """Build the Claude system prompt with all Gold table schemas embedded.

    Merges three layers of description for each table:
      1. Physical schema from Glue Catalog (column names + data types from SchemaResolver)
      2. Business context from dbt catalog.json (column descriptions, if pipeline has run)
      3. Static hints from GOLD_TABLE_CATALOG (accepted values, business meaning)

    If the live schema dict is empty (SchemaResolver could not reach Glue), falls back
    to the static catalog only — enough for Claude to function in offline/test mode.

    Args:
        schemas: AllSchemas dict from SchemaResolver.load_all_schemas().
        gold_database: Name of the Gold Glue database (e.g. 'edp_dev_gold').
        max_rows: Maximum rows Claude should return per query.

    Returns:
        Fully formatted system prompt string ready to pass to the Claude API.
    """
    schema_blocks: list[str] = []

    if schemas:
        for table_name, table_schema in schemas.items():
            block = _format_table_block(table_name, table_schema)
            schema_blocks.append(block)
    else:
        # Fallback: render from static catalog only (no live Glue data).
        for table_name, hints in GOLD_TABLE_CATALOG.items():
            block = _format_static_table_block(table_name, hints, gold_database)
            schema_blocks.append(block)

    schema_text = "\n\n".join(schema_blocks)

    return _SQL_SYSTEM_HEADER.format(
        gold_database=gold_database,
        max_rows=max_rows,
        schema_text=schema_text,
    )


def _format_table_block(table_name: str, table_schema: Any) -> str:
    """Format a live TableSchema, supplemented with static hints."""
    hints = GOLD_TABLE_CATALOG.get(table_name, {})

    # Prefer live dbt description; fall back to static hint.
    description = table_schema.description or hints.get("__table__", "")

    lines = [f"### {table_schema.database}.{table_name}"]
    if description:
        lines.append(description)
    if table_schema.partition_keys:
        lines.append(f"Partition keys: {', '.join(table_schema.partition_keys)}")
    lines.append("Columns:")

    for col in table_schema.columns:
        # Prefer dbt description; fall back to static hint for this column.
        col_desc = col.description or hints.get(col.name, "")
        suffix = f" — {col_desc}" if col_desc else ""
        lines.append(f"  {col.name} ({col.data_type}){suffix}")

    return "\n".join(lines)


def _format_static_table_block(
    table_name: str,
    hints: dict[str, str],
    gold_database: str,
) -> str:
    """Format a table block from the static catalog only (offline fallback)."""
    description = hints.get("__table__", "")
    lines = [f"### {gold_database}.{table_name}"]
    if description:
        lines.append(description)
    lines.append("Columns:")
    for col_name, col_desc in hints.items():
        if col_name == "__table__":
            continue
        lines.append(f"  {col_name} — {col_desc}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Message builders — SQL generation
# ---------------------------------------------------------------------------


def build_sql_request_messages(question: str) -> list[dict[str, str]]:
    """Build the initial messages list for a SQL generation request.

    Returns a single user message containing the plain-English question.
    The system prompt is passed separately to the Claude API call.
    """
    return [{"role": "user", "content": question}]


def build_sql_correction_messages(
    prior_messages: list[dict[str, str]],
    prior_sql: str,
    prior_assumptions: list[str],
    validation_reason: str,
) -> list[dict[str, str]]:
    """Extend the conversation with a correction turn.

    Reconstructs the assistant's previous response from the parsed sql and
    assumptions, then appends a user correction message explaining what
    was wrong. The generator calls this when the validator rejects the SQL.

    Args:
        prior_messages: The messages list used in the previous call.
        prior_sql: The SQL that failed validation.
        prior_assumptions: The assumptions list from the previous response.
        validation_reason: The reason string from SQLValidationError.reason.

    Returns:
        A new messages list with the assistant response + correction appended.
    """
    assumptions_text = "\n".join(f"- {a}" for a in prior_assumptions)
    assistant_content = (
        f"<sql>\n{prior_sql}\n</sql>\n" f"<assumptions>\n{assumptions_text}\n</assumptions>"
    )

    correction_content = (
        f"The SQL you generated failed a guardrail check:\n\n"
        f"{validation_reason}\n\n"
        f"Please fix the SQL so it passes that check and try again. "
        f"Return the same <sql> / <assumptions> format."
    )

    return [
        *prior_messages,
        {"role": "assistant", "content": assistant_content},
        {"role": "user", "content": correction_content},
    ]


# ---------------------------------------------------------------------------
# System prompt and message builders — insight generation
# ---------------------------------------------------------------------------

INSIGHT_SYSTEM_PROMPT: Final[str] = """\
You are a concise data analyst. You will be given a business question, \
the SQL query that answered it, and a sample of the results.

Always respond in the same language the question was asked in.

You must respond in exactly this format — no text before or after:

<chart_title>A short 5-8 word title describing what the chart shows. \
Same language as the question. No full stop.</chart_title>
<insight>
Your 2-3 sentence insight that directly answers the question. \
Start with the key finding. Include the most relevant number or comparison. \
Do not explain the SQL. Do not mention table names or column names. \
Do not use words like 'leverage', 'utilize', or 'robust'. \
Write as if talking to a non-technical business stakeholder.
</insight>

If the results section says "(no rows returned)", explain that the query returned \
no data matching the criteria and suggest the filter or time period may be too narrow. \
Still use the same format and language as the question.
"""


def build_insight_messages(
    question: str,
    sql: str,
    result_markdown: str,
) -> list[dict[str, str]]:
    """Build the messages list for insight generation.

    Args:
        question: The original plain-English question from the user.
        sql: The validated SQL that was executed.
        result_markdown: The query result formatted as a markdown table.

    Returns:
        Messages list for the insight Claude call.
    """
    content = (
        f"Question: {question}\n\n"
        f"SQL executed:\n```sql\n{sql}\n```\n\n"
        f"Results:\n{result_markdown}\n\n"
        f"Write a 2-3 sentence insight that directly answers the question."
    )
    return [{"role": "user", "content": content}]
